spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    cache-names: eventsList,publicEventDetail,adminEventDetail

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticketflow-mail-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hfing.ticketflowapi.notification.dto"
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM:no-reply@ticketflow.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB

aws:
  region:
    static: ${REGION}
  credentials:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
  s3:
    bucket-name: ${BUCKET_NAME}

vnpay:
  tmn-code: ${VNP_TMN_CODE}
  hash-secret: ${VNP_HASH_SECRET}
  pay-url: ${VNP_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNP_RETURN_URL:http://localhost:8080/api/v1/payments/vnpay-callback}
  expire-minutes: ${VNP_EXPIRE_MINUTES:5}
  expiration-scan-interval-ms: ${VNP_EXPIRATION_SCAN_INTERVAL_MS:10000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoint:
    health:
      show-details: always


