spring:
  application:
    name: ticketflow-api

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret-key: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: when-authorized

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true
